export enum MODALS {
  EDIT_PRODUCT = 'EDIT_PRODUCT',
  EDIT_EMERGENCY_PRODUCT = 'EDIT_EMERGENCY_PRODUCT',
  MINIMUM_PRODUCT_VALUE = 'MINIMUM_PRODUCT_VALUE',
  MONTHLY_PRE_ORDER = 'MONTHLY_PRE_ORDER',
  CONFIRM = 'CONFIRM',
  CONTACT = 'CONTACT',
  ONBOARDING = 'ONBOARDING',
  PRE_ORDER_DESCRIPTION = 'PRE_ORDER_DESCRIPTION',
  DEVOLUTION = 'DEVOLUTION',
  SALE_ORDER = 'SALE_ORDER',
  DEVOLUTION_ORDER = 'DEVOLUTION_ORDER',
  FINALIZE_ORDER = 'FINALIZE_ORDER',
  PLAN_EXCELLENCE = 'PLAN_EXCELLENCE',
  VIEW_ADMIN_MATERIAL = ' VIEW_ADMIN_MATERIAL',
  VIEW_ADMIN_GROUP = 'VIEW_ADMIN_GROUP',
  SOUL_COLLETION = 'SOUL_COLLETION',
  FRANCHISE_GROUP_SELECTION = 'FRANCHISE_GROUP_SELECTION',
  EDIT_PROFILE = 'EDIT_PROFILE',
  EMAIL = 'EMAIL'
}

export enum MODAL_TYPES {
  SIDE = 'SIDE',
  CENTER = 'CENTER',
}
